services:

  mongo:
    image: mongo:6
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: backend-app
    ports:
      - "8001:8001"
    environment:
      - PORT=8001
      - MONGO_URL=mongodb://mongo:27017/todo
    depends_on:
      - mongo
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend-app
    ports:
      - "3000:3000"
    depends_on:
      - backend
    stdin_open: true
    tty: true
    restart: always

volumes:
  mongo-data:
